-- MySQL Script generated by MySQL Workbench
-- Fri Apr 26 22:59:20 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`historial_clinico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`historial_clinico` (
  `id` INT NOT NULL,
  `id_user` INT NULL,
  `hisorial` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `id_user_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `id_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `mydb`.`USUARIOS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`laboratorios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`laboratorios` (
  `id` INT NOT NULL,
  `id_user` INT NOT NULL,
  `laboraorios` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_user_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `id_user0`
    FOREIGN KEY (`id_user`)
    REFERENCES `mydb`.`USUARIOS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`USUARIOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`USUARIOS` (
  `id` INT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `ciudad` VARCHAR(45) NOT NULL,
  `hitorial_id` INT NOT NULL,
  `laboratorios:id` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `historial_id_idx` (`hitorial_id` ASC) VISIBLE,
  CONSTRAINT `historial_id`
    FOREIGN KEY (`hitorial_id`)
    REFERENCES `mydb`.`historial_clinico` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `laboratorios_id`
    FOREIGN KEY ()
    REFERENCES `mydb`.`laboratorios` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`hospitales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`hospitales` (
  `id` INT NOT NULL,
  `ciudad_id` INT NULL,
  `camillas` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipo_cita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo_cita` (
  `id` INT NOT NULL,
  `especialidades` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`especialistas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`especialistas` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `ciudad` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `contraseña` VARCHAR(45) NOT NULL,
  `especialidad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`agendamiento_CITAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`agendamiento_CITAS` (
  `id` INT NOT NULL,
  `id_user` INT NOT NULL,
  `id_tipo_cita` INT NOT NULL,
  `ciudad_eps` VARCHAR(45) NOT NULL,
  `especialista_id` INT NOT NULL,
  `historial_id` INT NOT NULL,
  `laboratorios_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_user_idx` (`id_user` ASC) VISIBLE,
  INDEX `id_tipo_cita_idx` (`id_tipo_cita` ASC) VISIBLE,
  INDEX `especialista_id_idx` (`especialista_id` ASC) VISIBLE,
  INDEX `laboratorios:id_idx` (`laboratorios_id` ASC) VISIBLE,
  INDEX `historial_id_idx` (`historial_id` ASC) VISIBLE,
  CONSTRAINT `id_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `mydb`.`USUARIOS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_tipo_cita`
    FOREIGN KEY (`id_tipo_cita`)
    REFERENCES `mydb`.`tipo_cita` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `especialista_id`
    FOREIGN KEY (`especialista_id`)
    REFERENCES `mydb`.`especialistas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `laboratorios:id`
    FOREIGN KEY (`laboratorios_id`)
    REFERENCES `mydb`.`laboratorios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `historial_id`
    FOREIGN KEY (`historial_id`)
    REFERENCES `mydb`.`historial_clinico` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`medicamentos_list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`medicamentos_list` (
  `id` INT NOT NULL,
  `tipo_de_medicamento` VARCHAR(45) NOT NULL,
  `medicamento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`orden_medicamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`orden_medicamentos` (
  `id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `list_id` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `dosis` INT NOT NULL,
  `horario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
  INDEX `list_id_idx` (`list_id` ASC) VISIBLE,
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`USUARIOS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `list_id`
    FOREIGN KEY (`list_id`)
    REFERENCES `mydb`.`medicamentos_list` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ambulancias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ambulancias` (
  `id` INT NOT NULL,
  `ciudad_id` INT NULL,
  `cantidad` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`orden_de_emergencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`orden_de_emergencia` (
  `id` INT NOT NULL,
  `hospital_id` INT NULL,
  `ambulancia_id` INT NULL,
  `historial_id` INT NULL,
  `laboratorios_id` INT NULL,
  `user_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
  INDEX `hospital_id_idx` (`hospital_id` ASC) VISIBLE,
  INDEX `historial_id_idx` (`historial_id` ASC) VISIBLE,
  INDEX `laboratirios_id_idx` (`laboratorios_id` ASC) VISIBLE,
  INDEX `ambulacia_id_idx` (`ambulancia_id` ASC) VISIBLE,
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`USUARIOS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `hospital_id`
    FOREIGN KEY (`hospital_id`)
    REFERENCES `mydb`.`hospitales` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `historial_id`
    FOREIGN KEY (`historial_id`)
    REFERENCES `mydb`.`historial_clinico` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `laboratirios_id`
    FOREIGN KEY (`laboratorios_id`)
    REFERENCES `mydb`.`laboratorios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ambulacia_id`
    FOREIGN KEY (`ambulancia_id`)
    REFERENCES `mydb`.`ambulancias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`consulta_de_cita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`consulta_de_cita` (
  `id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `agendamiento_id` INT NOT NULL,
  `tipo_cita` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
  INDEX `agendamiento_id_idx` (`agendamiento_id` ASC) VISIBLE,
  INDEX `tipo_cita_id_idx` (`tipo_cita` ASC) VISIBLE,
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`USUARIOS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `agendamiento_id`
    FOREIGN KEY (`agendamiento_id`)
    REFERENCES `mydb`.`agendamiento_CITAS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `tipo_cita_id`
    FOREIGN KEY (`tipo_cita`)
    REFERENCES `mydb`.`tipo_cita` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
